### ISSUE TITLE
Error fetching candidates

### ISSUE THREAD

**Issue by arnau598** [ipb-halle/MetFragRelaunched#138] opened 2024-04-19 13:12 UTC
Greetings,

First of all I thank you for all the hard work on supporting this useful tool.

I've found an issue that says Error fetching candidates every time I want to search for a mass and I don't know how to continue.

I look forward to hearing from you.

**Comment by schymane** [comment] 2024-04-19 13:18
Can you provide more details next time please (e.g. web interface vs command line, which database you searched, what query...)?

@sneumann I can confirm that if I use KEGG or PubChem in the top menu items I also seem to get the same error, but if I use some of the local CSV options further down, I can get candidates. LipidMaps also fails, so it seems to affect the server databases?

PubChem top option with default example:
![image](https://github.com/ipb-halle/MetFragRelaunched/assets/4070141/8d243215-1608-4257-9e4c-212d7228fdd7)

KEGG (default example):
![image](https://github.com/ipb-halle/MetFragRelaunched/assets/4070141/b42c0a44-bf1b-467f-8f31-fbdc27fa51b9)

Using PubChemLite CSV, first one in the menu: 
![image](https://github.com/ipb-halle/MetFragRelaunched/assets/4070141/586035d0-d7bc-49d6-9b60-1ac20c317c21)

**Comment by schymane** [comment] 2024-04-19 13:20
@sneumann PS Beta seems to be working fine ... 

![image](https://github.com/ipb-halle/MetFragRelaunched/assets/4070141/291d6878-d55b-4f67-946e-ceb0e16204e7)

**Comment by arnau598** [comment] 2024-04-19 13:22
I wanted to use HMDB databases and Pubchem.

It seems it affects the database you choose.

**Comment by sneumann** [comment] 2024-04-22 09:08
Hi, I can confirm, I am on it. Yours, Steffen

**Comment by sneumann** [comment] 2024-04-22 11:01
Was a hickup in the underlying infrastructure, fixed now, thanks for reporting ! Yours, Steffen

**Closed by sneumann** 2024-04-22 11:01 UTC

**Comment by arnau598** [comment] 2024-04-22 11:03
Thank you very much Steffen!
